/* CHECK BODY LENGTH IS LESS TAHN 100KB*/
IF DATALENGTH(@Body) > 102400
BEGIN
  /* PROC RETURNS ERROR AT SEVERITY LEVEL 16 */
  RAISERROR ('Post body exceeds 100kB limit.', 16, 1)
  RETURN
END


/* pika chu */
